# @package datamodule.dataset_configs

pubchemqc-b3lyp-pm6:
  task_name: pubchemqc-b3lyp-pm6
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/pm6-HAD/
    raw_file_names: 
     - pm6-HAD_smiles.csv
    raw_label_file_names: 
     - pm6-HAD_labels.csv
    transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.standardizers.StandardizerFromStatFile
          statistics_file: "/db2/data/ADMET/data_final/data_refined/pm6-HAD/raw/stats.pt"
        - _target_: admet_prediction.datamodules.transforms.NanToNum
    pre_transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: null
