# @package system.task_head_configs

pubchemqc-b3lyp-pm6-ha:
  module:
    _target_: qip.taskheads.gps.SANGraphHead
    in_features: ${system.encoder_config.module.d_model}
    out_features: 2 # number of targets
    bias: True
  loss:
    _target_: torch.nn.SmoothL1Loss
  weight: 1.0
  metrics:
    - _target_: torchmetrics.MeanAbsoluteError
    - _target_: torchmetrics.PearsonCorrCoef
      num_outputs: 2
    - _target_: torchmetrics.SpearmanCorrCoef
      num_outputs: 2
  state_path: null
  post_process: null