# @package system.task_head_configs

clearance_hepatocyte_az:
  module:
    _target_: qip.taskheads.gps.SANGraphHead
    in_features: ${system.encoder_config.module.d_model}
    out_features: 1
    bias: True
  loss:
    _target_: torch.nn.SmoothL1Loss
  weight: 0.02
  metrics:
    - _target_: torchmetrics.SpearmanCorrCoef
      num_outputs: 1
  state_path: null
  post_process:
    _target_: qip.datamodules.transforms.standardizers.RescaleFromStatFile
    statistics_file: /db2/users/jungwookim/projects/QIP/datasets/admet_group/clearance_hepatocyte_az/raw/stats.pt
