# @package system.task_head_configs

dili:
  module:
    _target_: qip.taskheads.gps.SANGraphHead
    in_features: ${system.encoder_config.module.d_model}
    out_features: 1
    bias: True
  loss:
    _target_: qip.modules.losses.SigmoidFocalLoss
    alpha: 0.5092348284960422
  weight: 0.05
  metrics:
    - _target_: torchmetrics.classification.BinaryAUROC
  state_path: null
  post_process:
    _target_: torch.nn.Sigmoid