# @package system.task_head_configs

half_life_obach:
  module:
    _target_: admet_prediction.taskheads.gps.SANGraphHead
    in_features: ${system.encoder_config.module.d_model}
    out_features: 1
    bias: True
  loss:
    _target_: torch.nn.SmoothL1Loss
  weight: 0.011
  metrics:
    - _target_: torchmetrics.SpearmanCorrCoef
      num_outputs: 1
  state_path: null
  post_process:
    _target_: admet_prediction.datamodules.transforms.standardizers.RescaleFromStatFile
    statistics_file: /db2/data/ADMET/data_final/data_refined/TDC/half_life_obach/raw/stats.pt
