# @package system.task_head_configs

ld50_zhu:
  module:
    _target_: qip.taskheads.gps.SANGraphHead
    in_features: ${system.encoder_config.module.d_model}
    out_features: 1
    bias: True
  loss:
    _target_: torch.nn.SmoothL1Loss
  weight: 1.0858
  metrics:
    - _target_: torchmetrics.MeanAbsoluteError
  state_path: null
  post_process:
    _target_: qip.datamodules.transforms.standardizers.RescaleFromStatFile
    statistics_file: ${data_dir}/admet_group/ld50_zhu/raw/stats.pt
