# MT-0
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47800 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MT0.yaml seed=8252 name=layernorm_10k_gps_MT0_1_new trainer.max_steps=10000 trainer.devices=2
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47810 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MT0.yaml seed=8262 name=layernorm_10k_gps_MT0_2_new trainer.max_steps=10000 trainer.devices=2
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47820 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MT0.yaml seed=8272 name=layernorm_10k_gps_MT0_3_new trainer.max_steps=10000 trainer.devices=2
# MT- H
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47830 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTH.yaml seed=8252 name=layernorm_10k_gps_MTH_1_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTH/2023-09-27/11-22-40/checkpoints/checkpoint_000115128/encoder.pt
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47840 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTH.yaml seed=8262 name=layernorm_10k_gps_MTH_2_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTH/2023-09-27/11-22-40/checkpoints/checkpoint_000115128/encoder.pt
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47850 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTH.yaml seed=8272 name=layernorm_10k_gps_MTH_3_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTH/2023-09-27/11-22-40/checkpoints/checkpoint_000115128/encoder.pt
# MT- HA
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47860 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHA.yaml seed=8252 name=layernorm_10k_gps_MTHA_1_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTHA/2023-09-27/11-22-37/checkpoints/checkpoint_000094392/encoder.pt
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47870 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHA.yaml seed=8262 name=layernorm_10k_gps_MTHA_2_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTHA/2023-09-27/11-22-37/checkpoints/checkpoint_000094392/encoder.pt
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47880 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHA.yaml seed=8272 name=layernorm_10k_gps_MTHA_3_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTHA/2023-09-27/11-22-37/checkpoints/checkpoint_000094392/encoder.pt
# MT- HD
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47890 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHD.yaml seed=8252 name=layernorm_10k_gps_MTHD_1_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTHD/2023-09-27/11-22-37/checkpoints/checkpoint_000115640/encoder.pt
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47900 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHD.yaml seed=8262 name=layernorm_10k_gps_MTHD_2_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTHD/2023-09-27/11-22-37/checkpoints/checkpoint_000115640/encoder.pt
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47910 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHD.yaml seed=8272 name=layernorm_10k_gps_MTHD_3_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTHD/2023-09-27/11-22-37/checkpoints/checkpoint_000115640/encoder.pt
# MT- HAD
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47920 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHAD.yaml seed=8252 name=layernorm_10k_gps_MTHAD_1_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTHAD/2023-09-27/11-22-37/checkpoints/checkpoint_000110264/encoder.pt
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47930 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHAD.yaml seed=8262 name=layernorm_10k_gps_MTHAD_2_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTHAD/2023-09-27/11-22-37/checkpoints/checkpoint_000110264/encoder.pt
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47940 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHAD.yaml seed=8272 name=layernorm_10k_gps_MTHAD_3_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTHAD/2023-09-27/11-22-37/checkpoints/checkpoint_000110264/encoder.pt
# MT-R
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47950 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTR.yaml seed=8252 name=layernorm_10k_gps_MTR_1_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTR/2023-09-27/11-23-04/checkpoints/checkpoint_000149140/encoder.pt
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47960 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTR.yaml seed=8262 name=layernorm_10k_gps_MTR_2_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTR/2023-09-27/11-23-04/checkpoints/checkpoint_000149140/encoder.pt
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47970 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTR.yaml seed=8272 name=layernorm_10k_gps_MTR_3_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTR/2023-09-27/11-23-04/checkpoints/checkpoint_000149140/encoder.pt

# MT-R_only
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47950 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTR_only.yaml seed=8252 name=layernorm_10k_gps_MTR_only_1_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTR_only/2023-09-27/11-23-02/checkpoints/checkpoint_000143444/encoder.pt
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47960 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTR_only.yaml seed=8262 name=layernorm_10k_gps_MTR_only_2_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTR_only/2023-09-27/11-23-02/checkpoints/checkpoint_000143444/encoder.pt
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47970 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTR_only.yaml seed=8272 name=layernorm_10k_gps_MTR_only_3_new trainer.max_steps=10000 trainer.devices=2 system.encoder_config.state_path=/db2/users/jungwookim/projects/admet_prediction/outputs/train/runs/gps_PTR_only/2023-09-27/11-23-02/checkpoints/checkpoint_000143444/encoder.pt


# MT-HADR
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47800 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHADR.yaml seed=8252 name=layernorm_10k_gps_MTHADR_1_new trainer.max_steps=10000 trainer.devices=2
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47810 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHADR.yaml seed=8262 name=layernorm_10k_gps_MTHADR_2_new trainer.max_steps=10000 trainer.devices=2
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47820 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHADR.yaml seed=8272 name=layernorm_10k_gps_MTHADR_3_new trainer.max_steps=10000 trainer.devices=2
# MT-S
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47900 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTS.yaml seed=8252 name=layernorm_10k_gps_MTS_1_new trainer.max_steps=10000 trainer.devices=2
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47910 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTS.yaml seed=8262 name=layernorm_10k_gps_MTS_2_new trainer.max_steps=10000 trainer.devices=2
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47920 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTS.yaml seed=8272 name=layernorm_10k_gps_MTS_3_new trainer.max_steps=10000 trainer.devices=2
# MT-RS
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47930 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTRS.yaml seed=8252 name=layernorm_10k_gps_MTRS_1_new trainer.max_steps=10000 trainer.devices=2
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47940 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTRS.yaml seed=8262 name=layernorm_10k_gps_MTRS_2_new trainer.max_steps=10000 trainer.devices=2
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47950 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTRS.yaml seed=8272 name=layernorm_10k_gps_MTRS_3_new trainer.max_steps=10000 trainer.devices=2
# MT-HADRS
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47960 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHADRS.yaml seed=8252 name=layernorm_10k_gps_MTHADRS_1_new trainer.max_steps=10000 trainer.devices=2
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47970 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHADRS.yaml seed=8262 name=layernorm_10k_gps_MTHADRS_2_new trainer.max_steps=10000 trainer.devices=2
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47980 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHADRS.yaml seed=8272 name=layernorm_10k_gps_MTHADRS_3_new trainer.max_steps=10000 trainer.devices=2


# MT-HADR_only
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47830 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHADR_only.yaml seed=8252 name=layernorm_10k_gps_MTHADR_only_1_new trainer.max_steps=10000 trainer.devices=2
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47840 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHADR_only.yaml seed=8262 name=layernorm_10k_gps_MTHADR_only_2_new trainer.max_steps=10000 trainer.devices=2
HYDRA_FULL_ERROR=1 /db2/slurm_script/submit_job -N 1 -G 2 -C 32 -T dgx env MASTER_PORT=47850 /db2/users/jungwookim/mambaforge-pypy3/envs/grpe/bin/python run.py experiment=encoder_train/gps/multitask/gps_MTHADR_only.yaml seed=8272 name=layernorm_10k_gps_MTHADR_only_3_new trainer.max_steps=10000 trainer.devices=2
