name: qip
channels:
  - nvidia
  - pytorch
  - pyg
  - conda-forge
dependencies:
  - python=3.10
  - pytorch::pytorch>=2
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda==11.8
  - pyg::pyg
  - pyg::pytorch-scatter
  - lightning
  - hydra-core
  - hydra-colorlog
  - python-dotenv
  - rdkit
  - rich
  - pytdc