name: chemenv
channels:
  - openeye
  - rdkit
  - nvidia
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python~=3.10
  - lightning~=2.0.1
  - hydra-core==1.3.1
  - pytorch~=2.0.0
  - openeye-toolkits
  - torchvision
  - torchaudio
  - pytorch-cuda==11.7
  - scikit-learn
  - numpy
  - scipy
  - jupyter
  - ipython
  - rdkit
  - pandas
  - seaborn
  - matplotlib
  - tqdm
  - pyg
  - pylint
  - autopep8
  - pip
  - pip:
      - hydra-colorlog
      - hydra-optuna-sweeper
      - rich
      - libauc==1.2.0
      - ogb
      - python-dotenv
      - wandb
      - mlflow
      - onnx~=1.13.1
      - pre-commit
      - isort
      - black
      - pytest
      - transformers~=4.27.4
      - selfies~=2.1.1
      - torchmetrics
      - deepspeed
      - loguru
      - boto3
      - fastapi[all]
      - async-lru