name: qip
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.10
  # - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda
  # - cudatoolkit=11.8
  - lightning
  - pyg::pyg
  - pyg::pytorch-scatter
  - hydra-core
  - hydra-colorlog
  - python-dotenv
  - rdkit
  - rich
  - pytdc