defaults:
  - multidata.yaml
  - dataset_configs:
      - "CYP/1A2/v2_0_0"
      - "CYP/2C9/v2_0_0"
      - "CYP/2C19/v2_0_0"
      - "CYP/2D6/v2_0_0"
      - "CYP/3A4/v2_0_0"
      - "DILI/v2_0_0"
      - "HepaTox/v2_0_0"
      - "hERG/v2_2_0"
      - "lipophilicity/v1_0_0"
      - "LiverTox/v2_0_0"
      - "MS/human/v2_0_0"
      - "MS/mouse/v2_0_0"
      - "permeability/v2_0_0"
      - "pKa/acidic/v2_0_0"
      - "pKa/basic/v2_0_0"
      - "solubility/dmso/v2_0_0"
      - "solubility/pbs/v2_0_0"
      - "solubility/water/v2_0_0"
      - "tox21/nr_ahr/v2_0_0"
      - "tox21/nr_ar/v2_0_0"
      - "tox21/nr_ar_lbd/v2_0_0"
      - "tox21/nr_aromatase/v2_0_0"
      - "tox21/nr_er/v2_0_0"
      - "tox21/nr_er_lbd/v2_0_0"
      - "tox21/nr_ppar_gamma/v2_0_0"
      - "tox21/sr_are/v2_0_0"
      - "tox21/sr_atad5/v2_0_0"
      - "tox21/sr_hse/v2_0_0"
      - "tox21/sr_mmp/v2_0_0"
      - "tox21/sr_p53/v2_0_0"
      - "PubChemQC/v1_0_0"
      - "nablaDFT/v1_0_0"
