defaults:
  - gps/multidata_default.yaml
  - gps/dataset_configs:
      - "CYP/1A2/v3_0_0"
      - "CYP/2C9/v3_0_0"
      - "CYP/2C19/v2_0_0"
      - "CYP/2D6/v3_0_0"
      - "CYP/3A4/v3_0_0"
      - "hERG/v3_0_0"
      - "lipophilicity/v1_0_0"
      - "MS/human/v3_0_0"
      - "MS/mouse/v3_0_0"
      - "permeability/v3_0_0"
      - "solubility/pbs/v3_0_0"
      - "nablaDFT/v1_0_0"
      - "PubChemQC/v1_0_0"
