defaults:
  - gps/multidata_default.yaml
  - gps/dataset_configs:
      
      - "TDC/hia_hou/v1_0_0.yaml"
      - "TDC/pgp_broccatelli/v1_0_0.yaml"
      - "TDC/bioavailability_ma/v1_0_0.yaml"
      
      
      - "TDC/bbb_martins/v1_0_0.yaml"
      
      
      - "TDC/cyp2d6_veith/v1_0_0.yaml"
      - "TDC/cyp3a4_veith/v1_0_0.yaml"
      - "TDC/cyp2c9_veith/v1_0_0.yaml"
      - "TDC/cyp2d6_substrate_carbonmangels/v1_0_0.yaml"
      - "TDC/cyp3a4_substrate_carbonmangels/v1_0_0.yaml"
      - "TDC/cyp2c9_substrate_carbonmangels/v1_0_0.yaml"
      
      
      
      - "TDC/herg/v1_0_0.yaml"
      - "TDC/ames/v1_0_0.yaml"
      - "TDC/dili/v1_0_0.yaml"
      