defaults:
  - gps/multidata_default.yaml
  - gps/dataset_configs:
      - "TDC/caco2_wang/v1_0_0.yaml"
      - "TDC/hia_hou/v1_0_0.yaml"
      - "TDC/pgp_broccatelli/v1_0_0.yaml"
      - "TDC/bioavailability_ma/v1_0_0.yaml"
      - "TDC/lipophilicity_astrazeneca/v1_0_0.yaml"
      - "TDC/solubility_aqsoldb/v1_0_0.yaml"
      - "TDC/bbb_martins/v1_0_0.yaml"
      - "TDC/ppbr_az/v1_0_0.yaml"
      - "TDC/vdss_lombardo/v1_0_0.yaml"
      - "TDC/cyp2d6_veith/v1_0_0.yaml"
      - "TDC/cyp3a4_veith/v1_0_0.yaml"
      - "TDC/cyp2c9_veith/v1_0_0.yaml"
      - "TDC/cyp2d6_substrate_carbonmangels/v1_0_0.yaml"
      - "TDC/cyp3a4_substrate_carbonmangels/v1_0_0.yaml"
      - "TDC/cyp2c9_substrate_carbonmangels/v1_0_0.yaml"
      - "TDC/half_life_obach/v1_0_0.yaml"
      - "TDC/clearance_microsome_az/v1_0_0.yaml"
      - "TDC/clearance_hepatocyte_az/v1_0_0.yaml"
      - "TDC/herg/v1_0_0.yaml"
      - "TDC/ames/v1_0_0.yaml"
      - "TDC/dili/v1_0_0.yaml"
      - "TDC/ld50_zhu/v1_0_0.yaml"