# @package datamodule

_target_: qip.datamodules.multi.MultiDataModule
batch_size: 8 # default batch_size
split_val: True
num_workers: 0
collate_fn:
  _target_: qip.datamodules.collaters.DefaultCollater
  follow_batch: None
  exclude_keys: None