# @package datamodule

defaults:
  - gps/multidata_default.yaml
  - gps/dataset_configs:
      - "PubChemQC-B3LYP-PM6/v1_0_0"
      - "Desc/v1_0_0"
      - "grover/atom_v1_0_0"
      - "grover/fg_v1_0_0"

