# @package system.encoder_config
module:
  _target_: admet_prediction.encoders.grpe.MultitaskGRPEEncoder
  num_layer: 24
  d_model: 1536
  nhead: 32
  dim_feedforward: 3072
  dropout: 0.1
  attention_dropout: 0.1
  max_hop: 5
  # num_node_type: 190
  # num_edge_type: 18
  perturb_noise: 0.0
  norm_mode: "pre"
  task_names: "${oc.dict.keys: system.task_head_configs}"
state_path: null
