# @package datamodule.dataset_configs

ms-mouse:
  task_name: ms-mouse
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_finetuning/ms/mouse
    raw_file_names:
      - testset_smiles.csv
      - testset_smiles.csv
      - trainset_smiles.csv
    raw_label_file_names:
      - testset_labels.csv
      - testset_labels.csv
      - trainset_labels.csv
    transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.ShortestPathGenerator
        - _target_: admet_prediction.datamodules.transforms.OneHotEdgeAttr
  split_dict_name: "split_dict.pt" # cdd for test, anything else for train

