# @package datamodule.dataset_configs

cyp2d6_veith:
  task_name: cyp2d6_veith
  dataset:
    _target_: qip.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/TDC/cyp2d6_veith
    raw_file_names:
      - testset_smiles.csv
      - trainset_smiles.csv
    raw_label_file_names:
      - testset_labels.csv
      - trainset_labels.csv
    pre_transform:
      _target_: qip.datamodules.transforms.Compose
      transforms:
        - _target_: qip.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: "split_dict.pt"