# @package datamodule.dataset_configs

dacon-human:
  task_name: dacon-human
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/dacon_total/human/
    raw_file_names:
      - hlm_dacon_smiles.csv
      - hlm_chembl_smiles.csv
    raw_label_file_names:
      - hlm_dacon_labels_100.csv
      - hlm_chembl_labels_100.csv
    # transform:
    #   _target_: admet_prediction.datamodules.transforms.Compose
    #   transforms:
    #     - _target_: admet_prediction.datamodules.transforms.standardizers.StandardizerFromStatFile
    #       statistics_file: /db2/data/ADMET/data_final/data_refined/dacon/human/raw/stats_total.pt
    pre_transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: split_dict.pt # cdd for test, anything else for train

