# @package datamodule.dataset_configs

clearance_microsome_az:
  task_name: clearance_microsome_az
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/TDC/clearance_microsome_az
    raw_file_names:
      - testset_smiles.csv
      - trainset_smiles.csv
    raw_label_file_names:
      - testset_labels.csv
      - trainset_labels.csv
    transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.standardizers.StandardizerFromStatFile
          statistics_file: /db2/data/ADMET/data_final/data_refined/TDC/clearance_microsome_az/raw/stats.pt
    pre_transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: "split_dict.pt"