# @package datamodule.dataset_configs

dacon-mouse:
  task_name: dacon-mouse
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/dacon/pruned_hj/mouse/
    raw_file_names:
      - smiles.csv
    raw_label_file_names:
      - labels.csv
    # transform:
    #   _target_: admet_prediction.datamodules.transforms.Compose
    #   transforms:
    #     - _target_: admet_prediction.datamodules.transforms.standardizers.StandardizerFromStatFile
    #       statistics_file: /db2/data/ADMET/data_final/data_refined/dacon/human/raw/stats_onlydacon.pt
    pre_transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: null # cdd for test, anything else for train

