defaults:
  - multidata.yaml
  - dataset_configs:
      - "CYP/1A2/v3_0_0"
      - "CYP/2C9/v3_0_0"
      - "CYP/2C19/v3_0_0"
      - "CYP/2D6/v3_0_0"
      - "CYP/3A4/v3_0_0"
      - "hERG/v3_0_0"
      - "lipophilicity/v3_0_0"
      - "MS/human/v3_0_0"
      - "MS/mouse/v3_0_0"
      - "permeability/v3_0_0"
      - "solubility/pbs/v3_0_0"
      - "solubility/dmso/v1_1_0.yaml"
      - "solubility/water/v1_1_0.yaml"
      - "TDC/Caco2-Wang/v1_1_0.yaml"
      - "TDC/PAMPA-NCATS/v1_1_0.yaml"
      - "TDC/HIA-Hou/v1_1_0.yaml"
      - "TDC/Pgp-Broccatelli/v1_1_0.yaml"
      - "TDC/Bioavailability-Ma/v1_1_0.yaml"
      - "TDC/Lipophilicity-AstraZeneca/v1_1_0.yaml"
      - "TDC/Solubility-AqSolDB/v1_1_0.yaml"
      - "TDC/HydrationFreeEnergy-FreeSolv/v1_1_0.yaml"
      - "TDC/BBB-Martins/v1_1_0.yaml"
      - "TDC/PPBR-AZ/v1_1_0.yaml"
      - "TDC/VDss-LomBardo/v1_1_0.yaml"
      - "TDC/CYP2C19-Veith/v1_1_0.yaml"
      - "TDC/CYP2D6-Veith/v1_1_0.yaml"
      - "TDC/CYP3A4-Veith/v1_1_0.yaml"
      - "TDC/CYP1A2-Veith/v1_1_0.yaml"
      - "TDC/CYP2C9-Veith/v1_1_0.yaml"
      - "TDC/CYP2C9-Substrate-CarbonMangels/v1_1_0.yaml"
      - "TDC/CYP2D6-Substrate-CarbonMangels/v1_1_0.yaml"
      - "TDC/CYP3A4-Substrate-CarbonMangels/v1_1_0.yaml"
      - "TDC/Half-Life-Obach/v1_1_0.yaml"
      - "TDC/Clearance-Hepatocyte-AZ/v1_1_0.yaml"
      - "TDC/LD50-Zhu/v1_1_0.yaml"
      - "TDC/hERG/v1_1_0.yaml"
      - "TDC/hERG-Karim/v1_1_0.yaml"
      - "TDC/AMES/v1_1_0.yaml"
      - "TDC/DILI/v1_1_0.yaml"
      - "TDC/SkinReaction/v1_1_0.yaml"
      - "TDC/Carcinogens-Lagunin/v1_1_0.yaml"
      - "TDC/ClinTox/v1_1_0.yaml"
      - "pka/acidic/v1_1_0.yaml"
      - "pka/basic/v1_1_0.yaml"
      - "tox21/sr-mmp/v1_1_0.yaml"
      - "tox21/nr-er/v1_1_0.yaml"
      - "tox21/nr-aromatase/v1_1_0.yaml"
      - "tox21/nr-ahr/v1_1_0.yaml"
      - "tox21/sr-atad5/v1_1_0.yaml"
      - "tox21/sr-p53/v1_1_0.yaml"
      - "tox21/sr-hse/v1_1_0.yaml"
      - "tox21/sr-are/v1_1_0.yaml"
      - "tox21/nr-er-lbd/v1_1_0.yaml"
      - "tox21/nr-ppar-gamma/v1_1_0.yaml"
      - "tox21/nr-ar-lbd/v1_1_0.yaml"
      - "tox21/nr-ar/v1_1_0.yaml"
      - "dili/v1_1_0.yaml"
      - "hepatox/v1_1_0.yaml"
      - "livertox/v1_1_0.yaml"
