# @package system.task_head_configs

pubchemqc:
  module:
    _target_: admet_prediction.taskheads.gps.SANGraphHead
    in_features: ${system.encoder_config.module.d_model}
    out_features: 5 # number of targets
    bias: True
  loss:
    _target_: torch.nn.SmoothL1Loss
  weight: 1.0
  metrics:
    - _target_: torchmetrics.MeanAbsoluteError
    - _target_: torchmetrics.PearsonCorrCoef
    - _target_: torchmetrics.SpearmanCorrCoef
      num_outputs: 5
  state_path: null
  post_process: null