# @package datamodule.dataset_configs

desc:
  task_name: descriptors
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/unlabeled/
    raw_file_names: unlabeled_smiles.csv.gz
    raw_label_file_names: unlabeled_desc.csv.gz
    transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.ShortestPathGenerator
        - _target_: admet_prediction.datamodules.transforms.OneHotEdgeAttr
        - _target_: admet_prediction.datamodules.transforms.standardizers.StandardizerFromStatFile
          statistics_file: /db2/data/unlabeled/raw/statistics.pt
        - _target_: admet_prediction.datamodules.transforms.NanToNum
  split_dict_name: null
