# @package datamodule.dataset_configs

cyp-1a2: # dataset_name
  task_name: cyp-1a2 # task_name
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_finetuning/cyp/1A2/
    raw_file_names:
      - 1A2_cdd_smiles.csv
      - testset_smiles.csv
      - trainset_smiles.csv
      - 1A2_cdd_smiles.csv
      - testset_smiles.csv
    raw_label_file_names:
      - 1A2_cdd_labels.csv
      - testset_labels.csv
      - trainset_labels.csv
      - 1A2_cdd_labels.csv
      - testset_labels.csv
    transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.ShortestPathGenerator
        - _target_: admet_prediction.datamodules.transforms.OneHotEdgeAttr
  split_dict_name: "split_dict_serving.pt" # cdd for test, anything else for train
