# @package datamodule.dataset_configs

cyp-3a4: # dataset_name
  task_name: cyp-3a4 # task_name
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/cyp/3a4/
    raw_file_names:
      - 3A4_cdd_smiles.csv
      - testset_smiles.csv
      - trainset_smiles.csv
    raw_label_file_names:
      - 3A4_cdd_labels.csv
      - testset_labels.csv
      - trainset_labels.csv
    transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: "split_dict_serving.pt" # cdd for test, anything else for train
