# @package datamodule.dataset_configs

bbb_martins:
  task_name: bbb_martins
  dataset:
    _target_: qip.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/users/jungwookim/projects/QIP/datasets/admet_group/bbb_martins
    raw_file_names:
      - testset_smiles.csv
    transform:
      _target_: qip.datamodules.transforms.Compose
      transforms:
        - _target_: qip.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: "split_dict.pt"