# @package system.task_head_configs

grover-atom:
  module:
    _target_: qip.taskheads.grover.BondVocabHead
    dim_emb: ${system.encoder_config.module.d_model}
    vocab_size: 7493 # number of targets
    
  loss:
    _target_: torch.nn.NLLLoss
    ignore_index: 0
    reduction: mean
  weight: 1.0
  state_path: null
 