# @package datamodule.dataset_configs

lipophilicity_astrazeneca:
  task_name: lipophilicity_astrazeneca
  dataset:
    _target_: qip.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/users/jungwookim/projects/QIP/datasets/admet_group/lipophilicity_astrazeneca
    raw_file_names:
      - testset_smiles.csv
      - trainset_smiles.csv
    raw_label_file_names:
      - testset_labels.csv
      - trainset_labels.csv
    transform:
      _target_: qip.datamodules.transforms.Compose
      transforms:
        - _target_: qip.datamodules.transforms.standardizers.StandardizerFromStatFile
          statistics_file: ${data_dir}/admet_group/lipophilicity_astrazeneca/raw/stats.pt
        - _target_: qip.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: "split_dict.pt"