# @package datamodule.dataset_configs

cdd_cai2019:
  task_name: herg
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/herg/
    raw_file_names:
      - "herg_cdd_smiles.csv"
      - "herg_cai2019_smiles.csv"
    raw_label_file_names:
      - "herg_cdd_labels.csv"
      - "herg_cai2019_labels.csv"
    transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: "cddtest_split_dict.pt" # cdd for test, anything else for train

