# @package datamodule.dataset_configs

solubility-pbs:
  task_name: solubility-pbs
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_finetuning/solubility/pbs/
    raw_file_names:
      - testset_cdd_smiles.csv
      - testset_cdd_smiles.csv
      - trainset_smiles.csv
    raw_label_file_names:
      - testset_cdd_labels.csv
      - testset_cdd_labels.csv
      - trainset_labels.csv
    transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.ShortestPathGenerator
        - _target_: admet_prediction.datamodules.transforms.OneHotEdgeAttr
  split_dict_name: "split_dict_cddonly.pt" # cdd for test, anything else for train
