# @package datamodule.dataset_configs

descriptors:
  task_name: descriptors
  dataset:
    _target_: qip.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/descriptors_new
    raw_file_names:
      - tdc_smiles.csv
      - pm6_smiles.csv
    raw_label_file_names:
      - tdc_descs.csv
      - pm6_descs.csv
    transform:
      _target_: qip.datamodules.transforms.Compose
      transforms:
        - _target_: qip.datamodules.transforms.standardizers.StandardizerFromStatFile
          statistics_file: "/db2/data/ADMET/data_final/data_refined/descriptors_new/raw/stats.pt"
        - _target_: qip.datamodules.transforms.NanToNum
    transform:
      _target_: qip.datamodules.transforms.Compose
      transforms:
        - _target_: qip.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: null
