# @package callbacks

model_checkpoint:
  # _target_: lightning.pytorch.callbacks.ModelCheckpoint
  _target_: qip.callbacks.modelcheckpoint.ModelCheckpointWithSubModules
  monitor: "val/loss" # name of the logged metric which determines when model is improving
  mode: "min" # can be "max" or "min"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  verbose: False
  dirpath: "${work_dir}/checkpoints/"
  filename: "checkpoint_{step:09d}"
  auto_insert_metric_name: False
  submodule_names:
    - encoder
    - task_heads

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "step"

rich_progress_bar:
  _target_: lightning.pytorch.callbacks.RichProgressBar
  leave: True
