# @package system.task_head_configs

defaults:
  - "gps/task_head_default/CYP/cyp-1a2"
  - "gps/task_head_default/CYP/cyp-2c9"
  - "gps/task_head_default/CYP/cyp-2c19"
  - "gps/task_head_default/CYP/cyp-2d6"
  - "gps/task_head_default/CYP/cyp-3a4"
  - "gps/task_head_default/CYP/cyp-2b6"
  - "gps/task_head_default/CYP/cyp-2c8"
  - "gps/task_head_default/hERG/herg"
  - "gps/task_head_default/lipophilicity/lipophilicity"
  - "gps/task_head_default/MS/ms-human"
  - "gps/task_head_default/MS/ms-mouse"
  - "gps/task_head_default/permeability/permeability"
  - "gps/task_head_default/solubility/solubility-pbs"
  - "gps/task_head_default/nablaDFT/nabladft"
  - "gps/task_head_default/PubChemQC/pubchemqc"

cyp-1a2:
  weight: 0.03
cyp-2c9:
  weight: 0.03
cyp-2c19:
  weight: 0.03
cyp-2d6:
  weight: 0.03
cyp-3a4:
  weight: 0.03
cyp-2b6:
  weight: 0.03
cyp-2c8:
  weight: 0.03
herg:
  weight: 0.15
lipophilicity:
  weight: 0.15
ms-human:
  weight: 0.15
ms-mouse:
  weight: 0.15
permeability:
  weight: 0.15
solubility-pbs:
  weight: 0.15
nabladft:
  weight: 0.01
pubchemqc:
  weight: 0.01
