# @package system.task_head_configs

defaults:
  - "gps/task_head_default/CYP/cyp-1a2"
  - "gps/task_head_default/CYP/cyp-2c9"
  - "gps/task_head_default/CYP/cyp-2c19"
  - "gps/task_head_default/CYP/cyp-2d6"
  - "gps/task_head_default/CYP/cyp-3a4"
  - "gps/task_head_default/hERG/herg"
  - "gps/task_head_default/lipophilicity/lipophilicity"
  - "gps/task_head_default/MS/ms-human"
  - "gps/task_head_default/MS/ms-mouse"
  - "gps/task_head_default/permeability/permeability"
  - "gps/task_head_default/solubility/solubility-pbs"
  - "gps/task_head_default/nablaDFT/nabladft"
  - "gps/task_head_default/PubChemQC/pubchemqc"

  - "gps/task_head_default/solubility/solubility-dmso"
  - "gps/task_head_default/solubility/solubility-water"
  - "gps/task_head_default/TDC/TDC-Caco2-Wang"
  - "gps/task_head_default/TDC/TDC-PAMPA-NCATS"
  - "gps/task_head_default/TDC/TDC-HIA-Hou"
  - "gps/task_head_default/TDC/TDC-Pgp-Broccatelli"
  - "gps/task_head_default/TDC/TDC-Bioavailability-Ma"
  - "gps/task_head_default/TDC/TDC-Lipophilicity-AstraZeneca"
  - "gps/task_head_default/TDC/TDC-Solubility-AqSolDB"
  - "gps/task_head_default/TDC/TDC-HydrationFreeEnergy-FreeSolv"
  - "gps/task_head_default/TDC/TDC-BBB-Martins"
  - "gps/task_head_default/TDC/TDC-PPBR-AZ"
  - "gps/task_head_default/TDC/TDC-VDss-LomBardo"
  - "gps/task_head_default/TDC/TDC-CYP2C19-Veith"
  - "gps/task_head_default/TDC/TDC-CYP2D6-Veith"
  - "gps/task_head_default/TDC/TDC-CYP3A4-Veith"
  - "gps/task_head_default/TDC/TDC-CYP1A2-Veith"
  - "gps/task_head_default/TDC/TDC-CYP2C9-Veith"
  - "gps/task_head_default/TDC/TDC-CYP2C9-Substrate-CarbonMangels"
  - "gps/task_head_default/TDC/TDC-CYP2D6-Substrate-CarbonMangels"
  - "gps/task_head_default/TDC/TDC-CYP3A4-Substrate-CarbonMangels"
  - "gps/task_head_default/TDC/TDC-Half-Life-Obach"
  - "gps/task_head_default/TDC/TDC-Clearance-Hepatocyte-AZ"
  - "gps/task_head_default/TDC/TDC-LD50-Zhu"
  - "gps/task_head_default/TDC/TDC-hERG"
  - "gps/task_head_default/TDC/TDC-hERG-Karim"
  - "gps/task_head_default/TDC/TDC-AMES"
  - "gps/task_head_default/TDC/TDC-DILI"
  - "gps/task_head_default/TDC/TDC-SkinReaction"
  - "gps/task_head_default/TDC/TDC-Carcinogens-Lagunin"
  - "gps/task_head_default/TDC/TDC-ClinTox"
  - "gps/task_head_default/pka/pka-acidic"
  - "gps/task_head_default/pka/pka-basic"
  - "gps/task_head_default/tox21/tox21-sr-mmp"
  - "gps/task_head_default/tox21/tox21-nr-er"
  - "gps/task_head_default/tox21/tox21-nr-aromatase"
  - "gps/task_head_default/tox21/tox21-nr-ahr"
  - "gps/task_head_default/tox21/tox21-sr-atad5"
  - "gps/task_head_default/tox21/tox21-sr-p53"
  - "gps/task_head_default/tox21/tox21-sr-hse"
  - "gps/task_head_default/tox21/tox21-sr-are"
  - "gps/task_head_default/tox21/tox21-nr-er-lbd"
  - "gps/task_head_default/tox21/tox21-nr-ppar-gamma"
  - "gps/task_head_default/tox21/tox21-nr-ar-lbd"
  - "gps/task_head_default/tox21/tox21-nr-ar"
  - "gps/task_head_default/dili/dili"
  - "gps/task_head_default/hepatox/hepatox"
  - "gps/task_head_default/livertox/livertox"


cyp-1a2:
  weight: 0.03
cyp-2c9:
  weight: 0.03
cyp-2c19:
  weight: 0.03
cyp-2d6:
  weight: 0.03
cyp-3a4:
  weight: 0.03
herg:
  weight: 0.15
lipophilicity:
  weight: 0.15
ms-human:
  weight: 0.15
ms-mouse:
  weight: 0.15
permeability:
  weight: 0.15
solubility-pbs:
  weight: 0.15
nabladft:
  weight: 0.01
pubchemqc:
  weight: 0.01

solubility-dmso:
  weight: 0.15
solubility-water:
  weight: 0.15
TDC-Caco2-Wang:
  weight: 0.15
TDC-PAMPA-NCATS:
  weight: 0.15
TDC-HIA-Hou:
  weight: 0.15
TDC-Pgp-Broccatelli:
  weight: 0.15
TDC-BioavailabilityMa:
  weight: 0.15
TDC-Lipophilicity-AstraZeneca:
  weight: 0.15
TDC-Solubility-AqSolDB:
  weight: 0.15
TDC-HydrationFreeEnergy-FreeSolv:
  weight: 0.15
TDC-BBB-Martins:
  weight: 0.15
TDC-PPBR-AZ:
  weight: 0.15
TDC-VDss-LomBardo:
  weight: 0.15
TDC-CYP2C19-Veith:
  weight: 0.15
TDC-CYP2D6-Veith:
  weight: 0.15
TDC-CYP3A4-Veith:
  weight: 0.15
TDC-CYP1A2-Veith:
  weight: 0.15
TDC-CYP2C9-Veith:
  weight: 0.15
TDC-CYP2C9-Substrate-CarbonMangels:
  weight: 0.15
TDC-CYP2D6-Substrate-CarbonMangels:
  weight: 0.15
TDC-CYP3A4-Substrate-CarbonMangels:
  weight: 0.15
TDC-Half-Life-Obach:
  weight: 0.15
TDC-Clearance-Hepatocyte-AZ:
  weight: 0.15
TDC-LD50-Zhu:
  weight: 0.15
TDC-hERG:
  weight: 0.15
TDC-hERG-Karim:
  weight: 0.15
TDC-AMES:
  weight: 0.15
TDC-DILI:
  weight: 0.15
TDC-SkinReaction:
  weight: 0.15
TDC-Carcinogens-Lagunin:
  weight: 0.15
TDC-ClinTox:
  weight: 0.15
pka-acidic:
  weight: 0.15
pka-basic:
  weight: 0.15
tox21-sr-mmp:
  weight: 0.15
tox21-nr-er:
  weight: 0.15
tox21-nr-aromatase:
  weight: 0.15
tox21-nr-ahr:
  weight: 0.15
tox21-sr-atad5:
  weight: 0.15
tox21-sr-p53:
  weight: 0.15
tox21-sr-hse:
  weight: 0.15
tox21-sr-are:
  weight: 0.15
tox21-nr-er-lbd:
  weight: 0.15
tox21-nr-ppar-gamma:
  weight: 0.15
tox21-nr-ar-lbd:
  weight: 0.15
tox21-nr-ar:
  weight: 0.15
dili:
  weight: 0.15
hepatox:
  weight: 0.15
livertox:
  weight: 0.15