# @package system.task_head_configs

defaults:
  - "gps/task_head_default/TDC/TDC-Caco2-Wang"
  - "gps/task_head_default/TDC/TDC-PAMPA-NCATS"
  - "gps/task_head_default/TDC/TDC-HIA-Hou"
  - "gps/task_head_default/TDC/TDC-Pgp-Broccatelli"
  - "gps/task_head_default/TDC/TDC-Bioavailability-Ma"
  - "gps/task_head_default/TDC/TDC-Lipophilicity-AstraZeneca"
  - "gps/task_head_default/TDC/TDC-Solubility-AqSolDB"
  - "gps/task_head_default/TDC/TDC-HydrationFreeEnergy-FreeSolv"
  - "gps/task_head_default/TDC/TDC-BBB-Martins"
  - "gps/task_head_default/TDC/TDC-PPBR-AZ"
  - "gps/task_head_default/TDC/TDC-VDss-LomBardo"
  - "gps/task_head_default/TDC/TDC-CYP2C19-Veith"
  - "gps/task_head_default/TDC/TDC-CYP2D6-Veith"
  - "gps/task_head_default/TDC/TDC-CYP3A4-Veith"
  - "gps/task_head_default/TDC/TDC-CYP1A2-Veith"
  - "gps/task_head_default/TDC/TDC-CYP2C9-Veith"
  - "gps/task_head_default/TDC/TDC-CYP2C9-Substrate-CarbonMangels"
  - "gps/task_head_default/TDC/TDC-CYP2D6-Substrate-CarbonMangels"
  - "gps/task_head_default/TDC/TDC-CYP3A4-Substrate-CarbonMangels"
  - "gps/task_head_default/TDC/TDC-Half-Life-Obach"
  - "gps/task_head_default/TDC/TDC-Clearance-Hepatocyte-AZ"
  - "gps/task_head_default/TDC/TDC-LD50-Zhu"
  - "gps/task_head_default/TDC/TDC-hERG"
  - "gps/task_head_default/TDC/TDC-hERG-Karim"
  - "gps/task_head_default/TDC/TDC-AMES"
  - "gps/task_head_default/TDC/TDC-DILI"
  - "gps/task_head_default/TDC/TDC-SkinReaction"
  - "gps/task_head_default/TDC/TDC-Carcinogens-Lagunin"
  - "gps/task_head_default/TDC/TDC-ClinTox"


TDC-Caco2-Wang:
  weight: 0.15
TDC-PAMPA-NCATS:
  weight: 0.15
TDC-HIA-Hou:
  weight: 0.15
TDC-Pgp-Broccatelli:
  weight: 0.15
TDC-Bioavailability-Ma:
  weight: 0.15
TDC-Lipophilicity-AstraZeneca:
  weight: 0.15
TDC-Solubility-AqSolDB:
  weight: 0.15
TDC-HydrationFreeEnergy-FreeSolv:
  weight: 0.15
TDC-BBB-Martins:
  weight: 0.15
TDC-PPBR-AZ:
  weight: 0.15
TDC-VDss-LomBardo:
  weight: 0.15
TDC-CYP2C19-Veith:
  weight: 0.15
TDC-CYP2D6-Veith:
  weight: 0.15
TDC-CYP3A4-Veith:
  weight: 0.15
TDC-CYP1A2-Veith:
  weight: 0.15
TDC-CYP2C9-Veith:
  weight: 0.15
TDC-CYP2C9-Substrate-CarbonMangels:
  weight: 0.15
TDC-CYP2D6-Substrate-CarbonMangels:
  weight: 0.15
TDC-CYP3A4-Substrate-CarbonMangels:
  weight: 0.15
TDC-Half-Life-Obach:
  weight: 0.15
TDC-Clearance-Hepatocyte-AZ:
  weight: 0.15
TDC-LD50-Zhu:
  weight: 0.15
TDC-hERG:
  weight: 0.15
TDC-hERG-Karim:
  weight: 0.15
TDC-AMES:
  weight: 0.15
TDC-DILI:
  weight: 0.15
TDC-SkinReaction:
  weight: 0.15
TDC-Carcinogens-Lagunin:
  weight: 0.15
TDC-ClinTox:
  weight: 0.15