# @package system.task_head_configs

defaults:
  - "gps/task_head_default/TDC/caco2_wang.yaml"
  - "gps/task_head_default/TDC/hia_hou.yaml"
  - "gps/task_head_default/TDC/pgp_broccatelli.yaml"
  - "gps/task_head_default/TDC/bioavailability_ma.yaml"
  - "gps/task_head_default/TDC/lipophilicity_astrazeneca.yaml"
  - "gps/task_head_default/TDC/solubility_aqsoldb.yaml"
  - "gps/task_head_default/TDC/bbb_martins.yaml"
  - "gps/task_head_default/TDC/ppbr_az.yaml"
  - "gps/task_head_default/TDC/vdss_lombardo.yaml"
  - "gps/task_head_default/TDC/cyp2d6_veith.yaml"
  - "gps/task_head_default/TDC/cyp3a4_veith.yaml"
  - "gps/task_head_default/TDC/cyp2c9_veith.yaml"
  - "gps/task_head_default/TDC/cyp2d6_substrate_carbonmangels.yaml"
  - "gps/task_head_default/TDC/cyp3a4_substrate_carbonmangels.yaml"
  - "gps/task_head_default/TDC/cyp2c9_substrate_carbonmangels.yaml"
  - "gps/task_head_default/TDC/half_life_obach.yaml"
  - "gps/task_head_default/TDC/clearance_microsome_az.yaml"
  - "gps/task_head_default/TDC/clearance_hepatocyte_az.yaml"
  - "gps/task_head_default/TDC/herg.yaml"
  - "gps/task_head_default/TDC/ames.yaml"
  - "gps/task_head_default/TDC/dili.yaml"
  - "gps/task_head_default/TDC/ld50_zhu.yaml"
  - "gps/task_head_default/Dacon/human.yaml"
  - "gps/task_head_default/Dacon/mouse.yaml"
  - "gps/task_head_default/Dacon/shanghai2_hlm.yaml"
  - "gps/task_head_default/Dacon/shanghai2_market.yaml"
  - "gps/task_head_default/Dacon/shanghai2_rlm.yaml"
  - "gps/task_head_default/Dacon/usarmy_hlm.yaml"

caco2_wang:
  weight: 0.045
hia_hou:
  weight: 0.045
pgp_broccatelli:
  weight: 0.045
bioavailability_ma:
  weight: 0.045
lipophilicity_astrazeneca:
  weight: 0.045
solubility_aqsoldb:
  weight: 0.045
bbb_martins:
  weight: 0.045
ppbr_az:
  weight: 0.045
vdss_lombardo:
  weight: 0.045
cyp2d6_veith:
  weight: 0.045
cyp3a4_veith:
  weight: 0.045
cyp2c9_veith:
  weight: 0.045
cyp2d6_substrate_carbonmangels:
  weight: 0.045
cyp3a4_substrate_carbonmangels:
  weight: 0.045
cyp2c9_substrate_carbonmangels:
  weight: 0.045
half_life_obach:
  weight: 0.045
clearance_microsome_az:
  weight: 0.045
clearance_hepatocyte_az:
  weight: 0.045
herg:
  weight: 0.045
ames:
  weight: 0.045
dili:
  weight: 0.045
ld50_zhu:
  weight: 0.045
dacon-human:
  weight: 0.5
dacon-mouse:
  weight: 0.5

shanghai-human:
  weight: 0.045

shanghai-market:
  weight: 0.045

shanghai-rat:
  weight: 0.045

usarmy-human:
  weight: 0.045