# @package system.task_head_configs

defaults:
  - "gps/task_head_default/nablaDFT/nabladft"
  - "gps/task_head_default/PubChemQC/pubchemqc"
  - "gps/task_head_default/PubChemQC-B3LYP-PM6/pubchemqc-b3lyp-pm6"

nabladft:
  weight: 1
pubchemqc:
  weight: 1
pubchemqc-b3lyp-pm6:
  weight: 1
