# @package system.task_head_configs

defaults:
  - "gps/task_head_default/PubChemQC-B3LYP-PM6/pubchemqc-b3lyp-pm6"
  - "gps/task_head_default/Desc/descriptors"

pubchemqc-b3lyp-pm6:
  weight: 1

descriptors:
  weight: 1