# @package system.task_head_configs

defaults:
  - "gps/task_head_default/Desc/descriptors.yaml"
  - "gps/task_head_default/grover/grover_atom"
  - "gps/task_head_default/grover/grover_fg"

descriptors:
  weight: 0.42

grover-atom:
  weight: 0.04

grover-fg:
  weight: 0.04
