# @package datamodule.dataset_configs

permeability:
  task_name: permeability
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/hyunjun/
    raw_file_names:
      - hj_smiles.csv
    raw_label_file_names:

    transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.ShortestPathGenerator
        - _target_: admet_prediction.datamodules.transforms.OneHotEdgeAttr
  split_dict_name: "split_dict.pt" # cdd for test, anything else for train
