# @package datamodule.dataset_configs

nabladft:
  task_name: nabladft
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/benchmarks/nablaDFT/
    raw_file_names: nabladft_min_formation_smiles.csv
    raw_label_file_names: nabladft_min_formation_label.csv
    transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.ShortestPathGenerator
        - _target_: admet_prediction.datamodules.transforms.OneHotEdgeAttr
        - _target_: admet_prediction.datamodules.transforms.standardizers.NablaDFTStandardizer
        - _target_: admet_prediction.datamodules.transforms.NanToNum
  split_dict_name: null
  split_val: True
