# @package datamodule.dataset_configs

pubchemqc-b3lyp-pm6-hd:
  task_name: pubchemqc-b3lyp-pm6-hd
  dataset:
    _target_: qip.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/pm6-HD/
    raw_file_names: 
     - pm6-HD_smiles.csv
     - tdc_pm6-HD_smiles.csv
    raw_label_file_names: 
     - pm6-HD_labels.csv
     - tdc_pm6-HD_labels.csv
    transform:
      _target_: qip.datamodules.transforms.Compose
      transforms:
        - _target_: qip.datamodules.transforms.standardizers.StandardizerFromStatFile
          statistics_file: "/db2/data/ADMET/data_final/data_refined/pm6-HD/raw/stats.pt"
        - _target_: qip.datamodules.transforms.NanToNum
    pre_transform:
      _target_: qip.datamodules.transforms.Compose
      transforms:
        - _target_: qip.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: null
