# @package system.encoder_config

module:
  _target_: admet_prediction.encoders.gps.gnn.GNNEncoder
  model: gine
  d_model: 256
  nhead: 1
  dropout: 0.1
  layer_norm: True
  num_layer: 5
  
state_path: null