# @package system.encoder_config

module:
  _target_: admet_prediction.encoders.gps.model.GPSEncoder
  d_model: 384 # encoder_config의 dim_emb와 같은 값, nhead의 배수
  nhead: 16
  dropout: 0.1
  attention_dropout: 0.1
  layer_norm: True
  batch_norm: False
  momentum: 0.1
  log_attention_weights: True
  num_layer: 10
  encoder_config:
    node_config:
      dim_in: 1
      dim_posenc: 20
      dim_emb: 384 # layer_config의 dim_emb와 같은 값, nhead의 배수
      ksteps: [1,17] # datamodule/gps/datastconfigs에서 ksteps와 동일하게 맞춰야함.
      expand_x: False
      batch_norm: False
    edge_config:
      dim_emb: 384 # layer_config의 dim_emb와 같은 값, nhead의 배수
      batch_norm: False

state_path: null
