# @package datamodule.dataset_configs

cai2019only:
  task_name: herg
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/herg_separate/cai2019/
    raw_file_names:
      - testset_smiles.csv
      - herg_cai2019_smiles.csv
    raw_label_file_names:
      - testset_labels.csv
      - herg_cai2019_labels.csv
    transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.ShortestPathGenerator
        - _target_: admet_prediction.datamodules.transforms.OneHotEdgeAttr
  split_dict_name: "split_dict.pt" # cdd for test, anything else for train
