# @package datamodule.dataset_configs

central_cai:
  task_name: herg
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/herg_separate/central_cai/
    raw_file_names:
      - herg_cai2019_smiles.csv
      - herg_central_smiles.csv
    raw_label_file_names:
      - herg_cai2019_labels.csv
      - herg_central_labels.csv
    transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.ShortestPathGenerator
        - _target_: admet_prediction.datamodules.transforms.OneHotEdgeAttr
  split_dict_name: "split_dict.pt" # cdd for test, anything else for train
