# @package datamodule.dataset_configs

shanghai-rat:
  task_name: shanghai-rat
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/dacon/shanghai2/rat/
    raw_file_names:
      - rat_smiles.csv

    raw_label_file_names:
      - rat_labels.csv

    # transform:
    #   _target_: admet_prediction.datamodules.transforms.Compose
    #   transforms:
    #     - _target_: admet_prediction.datamodules.transforms.standardizers.StandardizerFromStatFile
    #       statistics_file: /db2/data/ADMET/data_final/data_refined/dacon/mouse/raw/stats_onlydacon.pt
    pre_transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: null # cdd for test, anything else for train

