# @package datamodule.dataset_configs

cyp3a4_veith:
  task_name: cyp3a4_veith
  dataset:
    _target_: qip.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/users/jungwookim/projects/QIP/datasets/admet_group/cyp3a4_veith
    raw_file_names:
      - testset_smiles.csv
      - trainset_smiles.csv
    raw_label_file_names:
      - testset_labels.csv
      - trainset_labels.csv
    transform:
      _target_: qip.datamodules.transforms.Compose
      transforms:
        - _target_: qip.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: "split_dict.pt"