# @package datamodule.dataset_configs

herg:
  task_name: herg
  dataset:
    _target_: qip.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: ${data_dir}/admet_group/herg
    raw_file_names:
      - testset_smiles.csv
      - trainset_smiles.csv
    raw_label_file_names:
      - testset_labels.csv
      - trainset_labels.csv
    transform:
      _target_: qip.datamodules.transforms.Compose
      transforms:
        - _target_: qip.datamodules.transforms.RandomWalkGenerator
          ksteps: [1,17]
          space_dim: 0
  split_dict_name: "split_dict.pt"