# @package datamodule.dataset_configs

pubchemqc-b3lyp-pm6:
  task_name: pubchemqc-b3lyp-pm6
  dataset:
    _target_: admet_prediction.datamodules.datasets.MoleculeGraphFromSMILESDataset
    root: /db2/data/ADMET/data_final/data_refined/pubchemqc-b3lyp-pm6/
    raw_file_names: smiles.csv
    raw_label_file_names: labels.csv
    transform:
      _target_: admet_prediction.datamodules.transforms.Compose
      transforms:
        - _target_: admet_prediction.datamodules.transforms.ShortestPathGenerator
        - _target_: admet_prediction.datamodules.transforms.OneHotEdgeAttr
        - _target_: admet_prediction.datamodules.transforms.standardizers.StandardizerFromStatFile
          statistics_file: "/db2/data/ADMET/data_final/data_refined/pubchemqc-b3lyp-pm6/raw/stats.pt"
        - _target_: admet_prediction.datamodules.transforms.NanToNum
  split_dict_name: null
  split_val: True
